baseURL = "https://arifrohman.com"
languageCode = 'en-us'
title = "Arif's Homepage"
theme = 'xmin'

[params]
  customCSS = ["css/custom.css"]

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  
[services.rss]
  limit = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]